create or replace view nba.nba_player_info_vw as

SELECT player_info.season,
    player_info.player_id,
    player_info.first_name,
    player_info.last_name,
    player_info.player_slug,
    player_info.birthdate,
    player_info.school,
    player_info.country,
    player_info.last_affiliation,
    player_info.height_cm,
    player_info.weight_kg,
    player_info.season_exp,
    player_info.jersey,
    player_info."position",
    player_info.rosterstatus,
    player_info.games_played_current_season_flag,
    player_info.team_id,
    player_info.team_name,
    player_info.team_abbreviation,
    player_info.team_code,
    player_info.team_city,
    player_info.playercode,
    player_info.from_year,
    player_info.to_year,
    player_info.dleague_flag,
    player_info.nba_flag,
    player_info.games_played_flag,
    player_info.draft_year,
    player_info.draft_round,
    player_info.draft_number,
    player_info.greatest_75_flag
   FROM nba.player_info;