CREATE OR REPLACE VIEW nba.nba_team_box_score_vw AS
SELECT 
	lgs.season,
    lgs.season_type,
    lgs.matchup,
    lgs.game_date,
    tbs.game_id,
    tbs.team_id,
    tbs.team_abbreviation,
    tbs.min,
    tbs.fgm,
    tbs.fga,
    tbs.fg_pct,
    tbs.fg3_m,
    tbs.fg3_a,
    tbs.fg3_pct,
    tbs.ftm,
    tbs.fta,
    tbs.ft_pct,
    tbs.pts,
    tbs.oreb,
    tbs.dreb,
    tbs.reb,
    tbs.ast,
    tbs.stl,
    tbs.blk,
    tbs.tov,
    tbs.pf,
    tbs.plus_minus,
    tbs.e_off_rating,
    tbs.off_rating,
    tbs.e_def_rating,
    tbs.def_rating,
    tbs.e_net_rating,
    tbs.net_rating,
    tbs.ast_pct,
    tbs.ast_tov,
    tbs.ast_ratio,
    tbs.oreb_pct,
    tbs.dreb_pct,
    tbs.reb_pct,
    tbs.e_tov_pct,
    tbs.tov_pct,
    tbs.efg_pct,
    tbs.ts_pct,
    tbs.usg_pct,
    tbs.e_usg_pct,
    tbs.e_pace,
    tbs.pace,
    tbs.pace_per40,
    tbs.poss,
    tbs.pie
   FROM nba.team_box_score tbs
     LEFT JOIN nba.league_game_schedule lgs 
     	ON tbs.game_id::double precision = lgs.game_id::double precision
     	AND tbs.team_abbreviation = lgs.team