name: Update Cockroach DB

on:
  push:
  schedule:
    - cron:  '0 3 * * *'

jobs:
    compile:
        name: Compile nba cockroach db
        runs-on: ubuntu-latest
        steps:
          - name: Check out repo
            uses: actions/checkout@v3
          - name: Run the build process with Docker
            uses: docker://shaggycamel/nba_cockroach_db:obtain-data